<?php include('includes/head_services.php'); ?>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
		<?php include_once("analyticstracking.php") ?>

        <?php include('includes/nav_services.php'); ?>

        <div class="container">

			<div class="main_content">
			<!-- Example row of columns -->
            <div class="row animated fadeInLeft">
                <?php include('includes/sidebar_nav_services.php'); ?>
				<div class="span8 margin_main_container">
					<div class="title_bkgd">
						<h1>Asset Maintenance</h1>
					</div>
					<img src="img/services/industrialcxmain.png" class="main_picture" alt="Head and Power Plant (UBC and NBC)">
					<p>
						Proper asset management allows organizations to ensure optimal use of their assets throughout their entire lifecycle.
					</p>
						
					<p>
						Maintenance and operations cover the useful life of the assets and represent the most important portion of building costs for the duration of the building life. Asset maintenance can take the form of various types of maintenance, including: preventive, repairs, improvements and renovations.
					</p>
						
					<p>
						Budgetary constraints are forcing companies to prioritize and decide between maintenance and replacement as part of their asset management activities.
					</p>
					
					<p>
						These choices, which are made in order to provide the best possible service to users, are based on knowledge of the following factors: the state of the assets, the strategic objectives of the organization as well as the types of maintenance completed or required and the associated costs.
					</p>

					<p>
						Proactive asset management requires four essential pieces of information:
						<ul>
							<li>Asset inventories, conditions, and technical and financial characteristics at the time of installation as well as updates throughout the life of the building;</li>							
							<li>The replacement value of assets that may require maintenance or replacement;</li>
							<li>The prioritization of systems (criticality) and buildings (role in the business mission);</li>
							<li>Asset management and maintenance history and planning information including related technical and financial information.</li>
						</ul>
					</p>
						
					<p>
						With the above information and good knowledge of the organization, CES Group deploys its asset management tool which operates continuously using data and information sourced from maintenance activities. This solution consists of:
						<ul>
							<li>Creating initial asset inventories that include their condition and attributes;</li>
							<li>Keeping the evolution of the assets’ conditions up to date using information generated by the ongoing maintenance, including asset management projects (history and planning);</li>
							<li>Define and quantify various indicators based on the role of the building;</li>
							<li>Providing supporting information (such as the Facility Condition Index) in order to make asset management decisions and develop an Investment Master Plan.</li>
						</ul>
					</p>

					<p>
						The supporting information and the format and content of the Master Plan are defined according to the needs and mission of the organization and in accordance with the asset management strategy.
					</p>

					<p>
						The database and maintenance solution used is called MMaint. In addition to containing all of the equipment information (inventory, maintenance and management) and financial information, this software solution is easy to implement, simple to learn, user-friendly, and is particularly reliable and affordable.
					</p>
					
					<p>
						Our implementation methodology is based on the involvement of various players in the organization and the establishment of tools in harmony with the environment in order to motivate these participants to use these tools properly as well as to remove the effect of incomplete or erroneous information. 
					</p>
				</div>
            </div>	
			</div>
			

         <?php include('includes/footer.php'); ?>

</div> <!-- /container -->

<?php include('includes/js.php'); ?>
    </body>
</html>
